# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "hexo" branch
  push:
    branches: [ "hexo" ]
  pull_request:
    branches: [ "hexo" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
        runs-on: ubuntu-18.04
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout source
              uses: actions/checkout@v2
              with:
                  ref: hexo
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12"
            - name: Setup Hexo
              env:
                  ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
              run: |
                  git config --global user.name "GitHub Action"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
                    echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"
                    echo "::set-output name=NO_PUSH::--no-push"
                  elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
                    echo "::set-output name=SRC_BRANCH::${GITHUB_REF#refs/heads/}"
                  fi
                  echo "::set-output name=DEPLOY_BRANCH::gh-pages"
                  npm install hexo-cli -g
                  npm install
            - name: Deploy
              run: |
                  hexo clean
                  hexo deploy
